
version: '3.0'
services:
  web:
    image: "michalbarczyk/io-lab-docker-ci-public:latest"
    # TODO: image, ports and redis dependency
    ports:
    - "80:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
